---
# 
version: '3'
services:
  elasticsearch:
    image: elasticsearch:7.16.1
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ports:
      - 9200:9200
      - 9300:9300
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3

  logstash:
    image: logstash:7.16.1
    environment:
      discovery.seed_hosts: logstash
      LS_JAVA_OPTS: "-Xms512m -Xmx512m"
    volumes:
      - logstash-volume:/usr/share/logstash/pipeline/logstash-nginx.config
      - logstash-volume:/home/nginx.log
    ports:
      - 5000:5000
      - 5044:5044
      - 9600:9600
    depends_on:
      - elasticsearch
    command: logstash -f /usr/share/logstash/pipeline/logstash-nginx.config
  kibana:
    image: kibana:7.16.1
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
volumes:
  logstash-volume:
